extend type Mutation {
  """
  ✨ Insert a single `Category` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  category_insert(
    """
    Data object to insert into the table.
    """
    data: Category_Data!
  ): Category_KeyOutput! @fdc_generated(from: "Category", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Document` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  document_insert(
    """
    Data object to insert into the table.
    """
    data: Document_Data!
  ): Document_KeyOutput! @fdc_generated(from: "Document", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `DocumentCategory` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  documentCategory_insert(
    """
    Data object to insert into the table.
    """
    data: DocumentCategory_Data!
  ): DocumentCategory_KeyOutput! @fdc_generated(from: "DocumentCategory", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `DocumentRating` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  documentRating_insert(
    """
    Data object to insert into the table.
    """
    data: DocumentRating_Data!
  ): DocumentRating_KeyOutput! @fdc_generated(from: "DocumentRating", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `FavoriteDocument` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  favoriteDocument_insert(
    """
    Data object to insert into the table.
    """
    data: FavoriteDocument_Data!
  ): FavoriteDocument_KeyOutput! @fdc_generated(from: "FavoriteDocument", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `User` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  user_insert(
    """
    Data object to insert into the table.
    """
    data: User_Data!
  ): User_KeyOutput! @fdc_generated(from: "User", purpose: INSERT_SINGLE)
  """
  ✨ Insert `Category` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  category_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Category_Data!]!
  ): [Category_KeyOutput!]! @fdc_generated(from: "Category", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Document` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  document_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Document_Data!]!
  ): [Document_KeyOutput!]! @fdc_generated(from: "Document", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `DocumentCategory` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  documentCategory_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [DocumentCategory_Data!]!
  ): [DocumentCategory_KeyOutput!]! @fdc_generated(from: "DocumentCategory", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `DocumentRating` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  documentRating_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [DocumentRating_Data!]!
  ): [DocumentRating_KeyOutput!]! @fdc_generated(from: "DocumentRating", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `FavoriteDocument` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  favoriteDocument_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [FavoriteDocument_Data!]!
  ): [FavoriteDocument_KeyOutput!]! @fdc_generated(from: "FavoriteDocument", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `User` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  user_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [User_Data!]!
  ): [User_KeyOutput!]! @fdc_generated(from: "User", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert or update a single `Category` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Category`.
  """
  category_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Category_Data!
  ): Category_KeyOutput! @fdc_generated(from: "Category", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Document` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Document`.
  """
  document_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Document_Data!
  ): Document_KeyOutput! @fdc_generated(from: "Document", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `DocumentCategory` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `DocumentCategory`.
  """
  documentCategory_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: DocumentCategory_Data!
  ): DocumentCategory_KeyOutput! @fdc_generated(from: "DocumentCategory", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `DocumentRating` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `DocumentRating`.
  """
  documentRating_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: DocumentRating_Data!
  ): DocumentRating_KeyOutput! @fdc_generated(from: "DocumentRating", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `FavoriteDocument` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `FavoriteDocument`.
  """
  favoriteDocument_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: FavoriteDocument_Data!
  ): FavoriteDocument_KeyOutput! @fdc_generated(from: "FavoriteDocument", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `User` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `User`.
  """
  user_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: User_Data!
  ): User_KeyOutput! @fdc_generated(from: "User", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update `Category` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Category`.
  """
  category_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Category_Data!]!
  ): [Category_KeyOutput!]! @fdc_generated(from: "Category", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Document` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Document`.
  """
  document_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Document_Data!]!
  ): [Document_KeyOutput!]! @fdc_generated(from: "Document", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `DocumentCategory` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `DocumentCategory`.
  """
  documentCategory_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [DocumentCategory_Data!]!
  ): [DocumentCategory_KeyOutput!]! @fdc_generated(from: "DocumentCategory", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `DocumentRating` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `DocumentRating`.
  """
  documentRating_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [DocumentRating_Data!]!
  ): [DocumentRating_KeyOutput!]! @fdc_generated(from: "DocumentRating", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `FavoriteDocument` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `FavoriteDocument`.
  """
  favoriteDocument_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [FavoriteDocument_Data!]!
  ): [FavoriteDocument_KeyOutput!]! @fdc_generated(from: "FavoriteDocument", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `User` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `User`.
  """
  user_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [User_Data!]!
  ): [User_KeyOutput!]! @fdc_generated(from: "User", purpose: UPSERT_MULTIPLE)
  """
  ✨ Update a single `Category` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Category` or `null` if not found.
  """
  category_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Category_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Category_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Category_Data!
  ): Category_KeyOutput @fdc_generated(from: "Category", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Document` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Document` or `null` if not found.
  """
  document_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Document_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Document_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Document_Data!
  ): Document_KeyOutput @fdc_generated(from: "Document", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `DocumentCategory` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `DocumentCategory` or `null` if not found.
  """
  documentCategory_update(
    """
    The key used to identify the object.
    """
    key: DocumentCategory_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: DocumentCategory_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: DocumentCategory_Data!
  ): DocumentCategory_KeyOutput @fdc_generated(from: "DocumentCategory", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `DocumentRating` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `DocumentRating` or `null` if not found.
  """
  documentRating_update(
    """
    The key used to identify the object.
    """
    key: DocumentRating_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: DocumentRating_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: DocumentRating_Data!
  ): DocumentRating_KeyOutput @fdc_generated(from: "DocumentRating", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `FavoriteDocument` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `FavoriteDocument` or `null` if not found.
  """
  favoriteDocument_update(
    """
    The key used to identify the object.
    """
    key: FavoriteDocument_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: FavoriteDocument_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: FavoriteDocument_Data!
  ): FavoriteDocument_KeyOutput @fdc_generated(from: "FavoriteDocument", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `User` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `User` or `null` if not found.
  """
  user_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: User_Data!
  ): User_KeyOutput @fdc_generated(from: "User", purpose: UPDATE_SINGLE)
  """
  ✨ Update `Category` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  category_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Category_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Category_Data!
  ): Int! @fdc_generated(from: "Category", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Document` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  document_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Document_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Document_Data!
  ): Int! @fdc_generated(from: "Document", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `DocumentCategory` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  documentCategory_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: DocumentCategory_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: DocumentCategory_Data!
  ): Int! @fdc_generated(from: "DocumentCategory", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `DocumentRating` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  documentRating_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: DocumentRating_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: DocumentRating_Data!
  ): Int! @fdc_generated(from: "DocumentRating", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `FavoriteDocument` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  favoriteDocument_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: FavoriteDocument_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: FavoriteDocument_Data!
  ): Int! @fdc_generated(from: "FavoriteDocument", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `User` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  user_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: User_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: User_Data!
  ): Int! @fdc_generated(from: "User", purpose: UPDATE_MULTIPLE)
  """
  ✨ Delete a single `Category` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  category_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Category_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Category_FirstRow
  ): Category_KeyOutput @fdc_generated(from: "Category", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Document` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  document_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Document_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Document_FirstRow
  ): Document_KeyOutput @fdc_generated(from: "Document", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `DocumentCategory` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  documentCategory_delete(
    """
    The key used to identify the object.
    """
    key: DocumentCategory_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: DocumentCategory_FirstRow
  ): DocumentCategory_KeyOutput @fdc_generated(from: "DocumentCategory", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `DocumentRating` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  documentRating_delete(
    """
    The key used to identify the object.
    """
    key: DocumentRating_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: DocumentRating_FirstRow
  ): DocumentRating_KeyOutput @fdc_generated(from: "DocumentRating", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `FavoriteDocument` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  favoriteDocument_delete(
    """
    The key used to identify the object.
    """
    key: FavoriteDocument_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: FavoriteDocument_FirstRow
  ): FavoriteDocument_KeyOutput @fdc_generated(from: "FavoriteDocument", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `User` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  user_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow
  ): User_KeyOutput @fdc_generated(from: "User", purpose: DELETE_SINGLE)
  """
  ✨ Delete `Category` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  category_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Category_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Category", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Document` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  document_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Document_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Document", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `DocumentCategory` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  documentCategory_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: DocumentCategory_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "DocumentCategory", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `DocumentRating` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  documentRating_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: DocumentRating_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "DocumentRating", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `FavoriteDocument` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  favoriteDocument_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: FavoriteDocument_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "FavoriteDocument", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `User` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  user_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: User_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "User", purpose: DELETE_MULTIPLE)
}
