#!/bin/bash
set -euo pipefail

# ensure-firebase-config.sh — guarantee every app target has a GoogleService-Info.plist
# to satisfy Xcode's CopyPlistFile resource phase during a build.
#
# Why this exists
# ---------------
# apple/project.yml lists `Apps/<APP>/GoogleService-Info.plist` as a bundle resource with
# `optional: true`. That flag only keeps **XcodeGen project generation** from failing when
# the file is missing — it does NOT stop Xcode's build-time CopyPlistFile phase from
# requiring the file, so an unsigned Debug/Release build dies with:
#   error: Build input file cannot be found: '.../Apps/PPL/GoogleService-Info.plist'
#
# The real per-app plists are intentionally NOT committed (each is downloaded from the
# Firebase console — see docs/RUNBOOK-ios-firebase.md) and Firebase isn't a package
# dependency yet (PlatformLive is Phase 4), so the plist is currently an inert bundled
# resource. This script writes a clearly-labelled, non-functional placeholder ONLY when a
# real plist is absent, so `swift`/`xcodebuild` can produce the offline app the repo already
# ships. A real plist that a developer or CI has dropped in is never overwritten.
#
# Usage:
#   ensure-firebase-config.sh <app|all>     # app ∈ ppl elpt aip cpl ir atpl
#
# Env:
#   FG_REQUIRE_REAL_FIREBASE=1   Fail (instead of stubbing) when a real plist is missing.
#                                Set this on any pipeline that must ship real Firebase config
#                                (e.g. a future signed production build) so a placeholder can
#                                never be uploaded silently.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
APPS_DIR="$PROJECT_ROOT/apple/Apps"

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; BLUE='\033[0;34m'; NC='\033[0m'
log_info()    { echo -e "${BLUE}ℹ${NC} $1"; }
log_success() { echo -e "${GREEN}✓${NC} $1"; }
log_warn()    { echo -e "${YELLOW}⚠${NC} $1"; }
log_error()   { echo -e "${RED}✗${NC} $1" >&2; }

ALL_APPS=("ppl" "elpt" "aip" "cpl" "ir" "atpl")

# app id -> "<AppDir> <bundle id>"
app_meta() {
  case "$1" in
    ppl)  echo "PPL com.flygaca.ppl" ;;
    elpt) echo "ELPT com.flygaca.elpt" ;;
    aip)  echo "AIP com.flygaca.aip" ;;
    cpl)  echo "CPL com.flygaca.cpl" ;;
    ir)   echo "IR com.flygaca.ir" ;;
    atpl) echo "ATPL com.flygaca.atpl" ;;
    *)    return 1 ;;
  esac
}

# Write a non-functional placeholder GoogleService-Info.plist for one app if none exists.
ensure_one() {
  local app="$1" meta app_dir bundle_id plist
  if ! meta="$(app_meta "$app")"; then
    log_error "Unknown app: $app (expected one of: ${ALL_APPS[*]})"
    return 1
  fi
  read -r app_dir bundle_id <<<"$meta"
  plist="$APPS_DIR/$app_dir/GoogleService-Info.plist"

  if [ -f "$plist" ]; then
    log_info "$app: GoogleService-Info.plist already present — leaving it untouched."
    return 0
  fi

  if [ "${FG_REQUIRE_REAL_FIREBASE:-}" = "1" ]; then
    log_error "$app: GoogleService-Info.plist missing and FG_REQUIRE_REAL_FIREBASE=1."
    echo "  Provide the real plist (docs/RUNBOOK-ios-firebase.md) before this build." >&2
    return 1
  fi

  if [ ! -d "$APPS_DIR/$app_dir" ]; then
    log_error "$app: app directory not found at $APPS_DIR/$app_dir"
    return 1
  fi

  # Obviously-placeholder values: the file only needs to exist and be a valid plist so the
  # CopyPlistFile phase succeeds. Firebase is not linked yet, so nothing reads these.
  cat > "$plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<!-- PLACEHOLDER — generated by scripts/native/ensure-firebase-config.sh. -->
	<!-- Not real Firebase config. Replace with the per-app plist from the Firebase -->
	<!-- console for any build that actually uses Firebase (docs/RUNBOOK-ios-firebase.md). -->
	<key>API_KEY</key>
	<string>PLACEHOLDER_NOT_A_REAL_API_KEY</string>
	<key>GCM_SENDER_ID</key>
	<string>000000000000</string>
	<key>PLIST_VERSION</key>
	<string>1</string>
	<key>BUNDLE_ID</key>
	<string>${bundle_id}</string>
	<key>PROJECT_ID</key>
	<string>flygaca-placeholder</string>
	<key>STORAGE_BUCKET</key>
	<string>flygaca-placeholder.appspot.com</string>
	<key>IS_ADS_ENABLED</key>
	<false/>
	<key>IS_ANALYTICS_ENABLED</key>
	<false/>
	<key>IS_APPINVITE_ENABLED</key>
	<false/>
	<key>IS_GCM_ENABLED</key>
	<true/>
	<key>IS_SIGNIN_ENABLED</key>
	<true/>
	<key>GOOGLE_APP_ID</key>
	<string>1:000000000000:ios:0000000000000000000000</string>
</dict>
</plist>
PLIST

  log_warn "$app: wrote placeholder GoogleService-Info.plist (Firebase inert — see docs/RUNBOOK-ios-firebase.md)."
}

main() {
  local target="${1:-all}"
  if [ ! -d "$APPS_DIR" ]; then
    log_error "apple/Apps not found at $APPS_DIR — run from the repo, nothing to do."
    exit 1
  fi

  if [ "$target" = "all" ]; then
    for a in "${ALL_APPS[@]}"; do ensure_one "$a"; done
  else
    ensure_one "$target"
  fi
}

main "${1:-all}"
